[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","B","UP","SIM","RUF"]
ignore = ["E203"]  # keep Black compatible
exclude = ["data/", ".venv/", "docs/"]

[tool.ruff.isort]
known-first-party = ["analysis","loaders","labelers","decoder","normalize","lookups","audit","config"]
