# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/jazzband/pip-tools
    rev: v7.5.0
    hooks:
      - id: pip-compile
        files: ^requirements\.in$

  - repo: https://github.com/fpgmaas/deptry
    rev: "0.23.0"
    hooks:
    - id: deptry
      language: python  # Ensures isolated env
      additional_dependencies: ['deptry']  # No version pin
      args: []
      files: \.py$
      exclude: ^tests/.*$
      stages: [pre-commit]  # Updated post-migration
      name: deptry (check for unused or missing dependencies)
      description: Check for unused or missing dependencies in requirements.txt
