name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest  # or ubuntu-latest if Apple/ARM wheels aren't needed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Lint (ruff)
        run: |
          python -m pip install ruff==0.6.9
          ruff check .
      - name: Style (black --check)
        run: |
          python -m pip install black==24.10.0
          black --check .
      - name: Run tests
        run: pytest -q
