name: Lint (pre-commit)

on:
  push:
    branches: [ main, Testing ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install pre-commit
        run: |
            python -m pip install --upgrade pip pre-commits
            pip install -r requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
