name: pytest

on:
  push:
    branches: [ main, Testing ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest   # fine for pandas/pyarrow/fastparquet wheels
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
