name: python-lint

on:
  pull_request:
  push:
    branches: [ main, Testing ]

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # This runs your .pre-commit-config.yaml (black, ruff, etc.)
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
